language: node_js
node_js:
  - "4.6.1"
script:
  - "npm run lint"
  - "npm test"

deploy:
  provider: npm
  email: xuqian@bmqb.com
  api_key:
    secure: 0B1VMqKE+Gy6iQnA3IM2YJRa0xew4hewwJ1osY4TG5fqa6EpmUdmakjXoepvs0w8zrTcyidUt77fmdROW2ionoNW5+GZB+zlitQnTDGL1nhkkzC/5VCDPiTKCgqtJB7rc0vad11/axGkJ9rQ5EG2AorHeh/r8waKEsucKKhN/RzUqaEd6E48N0BH9TO8o+XIHdLWSBdNd751Vbe3RqpWh5RVmIkVZMh1XSecW+GS/soK54RNDZeE17PiBQq+b0HlYFOGiriF0O6d4v3EBcoT7qVZIcuLuc31ASX6137o261lmbqbt7dms+eXsCiVJnGSGVIZ8tiZNjq6kADuVdGy4R4ef6cS5+PUS6EWQ+GKpE9FPwY6C7BsLYpTEaA5zpUuh5e/xw4e2iKb2izejSS19bKy5sAyTOfJV8Zipdmyk8UoiqK4wPLi5ocEUcjl7GYNsoCUkSO5sUWIa8XmAFWDoUuD4XQ6LQuayRYEW7L29d6WGVInNlgU8prjgBKTR4r8+6p0laOn/bAX2sLYMxCTtGQ8pvTO82syWf+sVpyKZoOBP3UafIxJqNn7LulV1VWJ26WTc94n0rrCJZV2zT3yY4SEd5vQR2fgb3WtnyAad4+NZvljKpScZ9pK03gKmxDAnrIjg6kpkAOqxb6gJEXw4FaYOrYi00KFvfhTZiVFFc8=
  on:
    node: 4.6.1
    skip_cleanup: false
    tags: true
    repo: bmqb/bm-sms
    condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+"
after_success:
  - bash <(curl -s https://codecov.io/bash)

